"""Adaptive conformal prediction (Gibbs & Candès 2021).

Online update rule for q_hat. Given a target miscoverage α, the
calibrated threshold is updated on each observation by

    q_{t+1} = q_t + γ · (α - 1{y_t ∉ C_t(q_t)})

where γ > 0 is a learning rate, 1{…} is the indicator that the
ground-truth label fell outside the prediction set at step t.

Coverage guarantee (Gibbs 2021 Thm 1): for any sequence of
observations, the long-run empirical miscoverage converges to α at
a 1/T rate. Critically, this is distribution-free — it holds under
arbitrary covariate shift, as long as the indicator 1{y_t ∉ C_t} is
observed at every step.

This file implements the scalar update rule as a pure function. The
deployment wiring (hook into the conformal service's post-query
feedback loop) is out of scope for this PR; the paper focuses on the
estimator and its coverage properties.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class AdaptiveState:
    q_hat: float
    step: int
    alpha: float
    gamma: float


def initial_state(*, alpha: float, gamma: float, q_hat_0: float = 0.5) -> AdaptiveState:
    """Fresh adaptive CP state.

    `alpha` is target miscoverage (e.g. 0.10 for 90% coverage).
    `gamma` is the learning rate — larger γ adapts faster at the cost
    of higher variance. Gibbs recommends γ ∈ [0.005, 0.05] for clinical
    workloads.
    """
    if not (0.0 < alpha < 1.0):
        raise ValueError(f"alpha must be in (0, 1); got {alpha}")
    if gamma <= 0.0:
        raise ValueError(f"gamma must be > 0; got {gamma}")
    return AdaptiveState(q_hat=q_hat_0, step=0, alpha=alpha, gamma=gamma)


def update(state: AdaptiveState, *, covered: bool) -> AdaptiveState:
    """One online step.

    `covered` is True iff the current test point's true label fell
    inside the prediction set constructed at threshold q_hat. The
    update shrinks q_hat when we're over-covering and grows it when
    we're under-covering, driving the empirical miscoverage toward α.
    """
    # miscov_indicator = 1 if NOT covered, 0 otherwise
    miscov = 0 if covered else 1
    new_q = state.q_hat + state.gamma * (state.alpha - miscov)
    return AdaptiveState(
        q_hat=new_q,
        step=state.step + 1,
        alpha=state.alpha,
        gamma=state.gamma,
    )


def run_sequence(
    *,
    alpha: float,
    gamma: float,
    coverage_feedback: list[bool],
    q_hat_0: float = 0.5,
) -> list[AdaptiveState]:
    """Replay a coverage-feedback sequence. Returns state at every step.

    The terminal state's `q_hat` is the converged estimate under the
    observed stream. Useful for the Paper P2 synthetic-shift figures
    where the sequence is generated by a known data-generating process.
    """
    state = initial_state(alpha=alpha, gamma=gamma, q_hat_0=q_hat_0)
    history: list[AdaptiveState] = [state]
    for covered in coverage_feedback:
        state = update(state, covered=covered)
        history.append(state)
    return history


def long_run_miscoverage(history: list[AdaptiveState]) -> float:
    """Empirical miscoverage across a history's updates.

    Given the sequence of (covered, not-covered) observations we can
    recover the miscoverage rate from the state trajectory: each
    step's q-change is `γ(α - miscov_indicator)`, so
    `miscov_indicator = α - (q_{t+1} - q_t)/γ` per step. Average
    over all steps.

    Not a replacement for recording the raw indicators — this is a
    diagnostic to verify run_sequence produces consistent states.
    """
    if len(history) < 2:
        return 0.0
    gamma = history[0].gamma
    alpha = history[0].alpha
    total = 0
    n = len(history) - 1
    for prev, curr in zip(history, history[1:], strict=False):
        dq = curr.q_hat - prev.q_hat
        # dq = gamma * (alpha - miscov); miscov = alpha - dq/gamma
        miscov_indicator = alpha - dq / gamma
        # Round defensively — inputs are 0 or 1.
        total += 1 if miscov_indicator > 0.5 else 0
    return total / n
