#!/usr/bin/env bash
# Generate the grafana-dashboards-json ConfigMap from the dashboard
# JSON files checked into docs/observability/dashboards/.
#
# Usage:
#   scripts/observability/build_dashboards_configmap.sh > /tmp/cm.yaml
#   kubectl apply -f /tmp/cm.yaml
#
# Output is idempotent: re-running with the same inputs produces the
# same YAML. Suitable for piping into `kubectl apply` and for GitOps
# flows.

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
dashboards_dir="${repo_root}/docs/observability/dashboards"

if [ ! -d "$dashboards_dir" ]; then
  echo "dashboards dir not found: $dashboards_dir" >&2
  exit 2
fi

cat <<'HEADER'
# Generated by scripts/observability/build_dashboards_configmap.sh.
# Do NOT hand-edit. Source of truth is docs/observability/dashboards/.
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-json
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: afya-sahihi
  annotations:
    afya-sahihi.aku.edu/source: scripts/observability/build_dashboards_configmap.sh
data:
HEADER

shopt -s nullglob
for f in "$dashboards_dir"/*.json; do
  name="$(basename "$f")"
  printf '  %s: |\n' "$name"
  # Indent each line of the JSON by 4 spaces so it nests under `    `
  # (the YAML block-scalar indicator `|` requires consistent indent).
  sed 's/^/    /' "$f"
done
